// <auto-generated />
using System;
using Jimaco.Aprobaciones.Modelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jimaco.Aprobaciones.Modelo.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902182805_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstanciaDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstanciaDocumentoId");

                    b.HasIndex("SubidoPorUsuarioId");

                    b.ToTable("Adjuntos");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.CampoTipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpcionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<int>("TipoCampo")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId", "Nombre")
                        .IsUnique();

                    b.ToTable("CamposTipoDocumento");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.DefinicionFlujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("DefinicionesFlujo");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.HistorialAccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstanciaDocumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("PasoFlujoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstanciaDocumentoId");

                    b.HasIndex("PasoFlujoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialAcciones");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.InstanciaDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("DatosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefinicionFlujoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PasoActualId")
                        .HasColumnType("int");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("DefinicionFlujoId");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroReferencia");

                    b.HasIndex("PasoActualId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("InstanciasDocumento");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstanciaDocumentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstanciaDocumentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefinicionFlujoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int?>("PasoDestinoDevolucionId")
                        .HasColumnType("int");

                    b.Property<bool>("PermiteDevolver")
                        .HasColumnType("bit");

                    b.Property<bool>("PermiteRechazar")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PasoDestinoDevolucionId");

                    b.HasIndex("DefinicionFlujoId", "Orden")
                        .IsUnique();

                    b.ToTable("PasosFlujo");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujoRol", b =>
                {
                    b.Property<int>("PasoFlujoId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("PasoFlujoId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("PasoFlujoRoles");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Administra usuarios, roles, tipos de documento y flujos.",
                            Nombre = "Admin"
                        });
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Adjunto", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.InstanciaDocumento", "InstanciaDocumento")
                        .WithMany("Adjuntos")
                        .HasForeignKey("InstanciaDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", "SubidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstanciaDocumento");

                    b.Navigation("SubidoPorUsuario");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.CampoTipoDocumento", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany("Campos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.DefinicionFlujo", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany("DefinicionesFlujo")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.HistorialAccion", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.InstanciaDocumento", "InstanciaDocumento")
                        .WithMany("Historial")
                        .HasForeignKey("InstanciaDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", "PasoFlujo")
                        .WithMany()
                        .HasForeignKey("PasoFlujoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstanciaDocumento");

                    b.Navigation("PasoFlujo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.InstanciaDocumento", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.DefinicionFlujo", "DefinicionFlujo")
                        .WithMany()
                        .HasForeignKey("DefinicionFlujoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", "PasoActual")
                        .WithMany()
                        .HasForeignKey("PasoActualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("DefinicionFlujo");

                    b.Navigation("PasoActual");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Notificacion", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.InstanciaDocumento", "InstanciaDocumento")
                        .WithMany()
                        .HasForeignKey("InstanciaDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstanciaDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.DefinicionFlujo", "DefinicionFlujo")
                        .WithMany("Pasos")
                        .HasForeignKey("DefinicionFlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", "PasoDestinoDevolucion")
                        .WithMany()
                        .HasForeignKey("PasoDestinoDevolucionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefinicionFlujo");

                    b.Navigation("PasoDestinoDevolucion");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujoRol", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", "PasoFlujo")
                        .WithMany("PasoFlujoRoles")
                        .HasForeignKey("PasoFlujoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Rol", "Rol")
                        .WithMany("PasoFlujoRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PasoFlujo");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.UsuarioRol", b =>
                {
                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.DefinicionFlujo", b =>
                {
                    b.Navigation("Pasos");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.InstanciaDocumento", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.PasoFlujo", b =>
                {
                    b.Navigation("PasoFlujoRoles");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Rol", b =>
                {
                    b.Navigation("PasoFlujoRoles");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.TipoDocumento", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("DefinicionesFlujo");
                });

            modelBuilder.Entity("Jimaco.Aprobaciones.Modelo.Entidades.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
